export type Job = {
  id: string;
  title: string;
  company: string;
  department: "Engineering" | "Data & AI" | "Product" | "People" | "Sales" | "Operations" | "Cloud & DevOps" | "Cybersecurity";
  location: string;
  remote: "On-site" | "Hybrid" | "Remote";
  type: "Full-time" | "Contract" | "Contract-to-Hire";
  experience: string;
  salaryRange: string;
  skills: string[];
  posted: string;
  featured?: boolean;
  urgent?: boolean;
};

export const jobs: Job[] = [
  {
    id: "LT-2026-001",
    title: "Senior Java Backend Engineer",
    company: "BFSI Client (Confidential)",
    department: "Engineering",
    location: "Hyderabad",
    remote: "Hybrid",
    type: "Full-time",
    experience: "6 – 10 yrs",
    salaryRange: "₹28 – 42 LPA",
    skills: ["Java 17", "Spring Boot", "Kafka", "AWS", "Microservices"],
    posted: "2 days ago",
    featured: true,
    urgent: true,
  },
  {
    id: "LT-2026-002",
    title: "Lead Data Scientist — GenAI",
    company: "Global Retail Major",
    department: "Data & AI",
    location: "Bengaluru",
    remote: "Hybrid",
    type: "Full-time",
    experience: "7 – 12 yrs",
    salaryRange: "₹40 – 60 LPA",
    skills: ["LLMs", "PyTorch", "MLOps", "Python", "Vector DBs"],
    posted: "1 day ago",
    featured: true,
  },
  {
    id: "LT-2026-003",
    title: "Talent Acquisition Lead",
    company: "Logos Trinity Technologies",
    department: "People",
    location: "Visakhapatnam",
    remote: "On-site",
    type: "Full-time",
    experience: "5 – 9 yrs",
    salaryRange: "₹14 – 22 LPA",
    skills: ["Tech Hiring", "Stakeholder Mgmt", "ATS", "Headhunting"],
    posted: "3 days ago",
    featured: true,
  },
  {
    id: "LT-2026-004",
    title: "Cloud DevOps Architect",
    company: "Enterprise SaaS",
    department: "Cloud & DevOps",
    location: "Pune",
    remote: "Remote",
    type: "Contract-to-Hire",
    experience: "8 – 12 yrs",
    salaryRange: "₹35 – 55 LPA",
    skills: ["AWS", "Terraform", "Kubernetes", "GitOps", "Observability"],
    posted: "4 days ago",
    featured: true,
  },
  {
    id: "LT-2026-005",
    title: "Senior React Engineer",
    company: "FinTech Unicorn",
    department: "Engineering",
    location: "Bengaluru",
    remote: "Hybrid",
    type: "Full-time",
    experience: "4 – 8 yrs",
    salaryRange: "₹22 – 38 LPA",
    skills: ["React", "TypeScript", "Next.js", "GraphQL", "Design Systems"],
    posted: "5 days ago",
    featured: true,
  },
  {
    id: "LT-2026-006",
    title: "Application Security Engineer",
    company: "Confidential — Govt. Sector",
    department: "Cybersecurity",
    location: "Chennai",
    remote: "On-site",
    type: "Full-time",
    experience: "5 – 9 yrs",
    salaryRange: "₹24 – 36 LPA",
    skills: ["OWASP", "SAST/DAST", "Threat Modelling", "Cloud Security"],
    posted: "1 week ago",
  },
  {
    id: "LT-2026-007",
    title: "Product Manager — Enterprise",
    company: "B2B SaaS",
    department: "Product",
    location: "Bengaluru / Visakhapatnam",
    remote: "Hybrid",
    type: "Full-time",
    experience: "5 – 8 yrs",
    salaryRange: "₹28 – 42 LPA",
    skills: ["Roadmapping", "B2B SaaS", "Discovery", "Analytics"],
    posted: "6 days ago",
  },
  {
    id: "LT-2026-008",
    title: "Enterprise Sales Manager",
    company: "Logos Trinity Technologies",
    department: "Sales",
    location: "Mumbai",
    remote: "Hybrid",
    type: "Full-time",
    experience: "6 – 10 yrs",
    salaryRange: "₹18 – 30 LPA + variable",
    skills: ["Enterprise Sales", "Staffing", "RFP", "C-level Engagement"],
    posted: "2 days ago",
  },
  {
    id: "LT-2026-009",
    title: "Site Reliability Engineer (SRE)",
    company: "Healthcare Platform",
    department: "Cloud & DevOps",
    location: "Hyderabad",
    remote: "Remote",
    type: "Contract",
    experience: "5 – 9 yrs",
    salaryRange: "₹26 – 40 LPA",
    skills: ["SLOs", "Prometheus", "GCP", "Incident Mgmt"],
    posted: "3 days ago",
  },
  {
    id: "LT-2026-010",
    title: "Operations Lead — Workforce Mgmt",
    company: "Logos Trinity Technologies",
    department: "Operations",
    location: "Visakhapatnam",
    remote: "On-site",
    type: "Full-time",
    experience: "6 – 10 yrs",
    salaryRange: "₹12 – 18 LPA",
    skills: ["WFM", "Payroll", "Compliance", "Stakeholder Mgmt"],
    posted: "1 day ago",
  },
  {
    id: "LT-2026-011",
    title: "ML Platform Engineer",
    company: "AI Startup (Series B)",
    department: "Data & AI",
    location: "Bengaluru",
    remote: "Hybrid",
    type: "Full-time",
    experience: "4 – 7 yrs",
    salaryRange: "₹30 – 50 LPA",
    skills: ["MLOps", "Ray", "Kubernetes", "Feature Stores"],
    posted: "4 days ago",
  },
  {
    id: "LT-2026-012",
    title: "UX Designer — Enterprise SaaS",
    company: "Logistics Tech",
    department: "Product",
    location: "Remote (India)",
    remote: "Remote",
    type: "Full-time",
    experience: "4 – 7 yrs",
    salaryRange: "₹18 – 28 LPA",
    skills: ["Figma", "Design Systems", "User Research", "Prototyping"],
    posted: "1 week ago",
  },
];

export const departments = [
  "All",
  "Engineering",
  "Data & AI",
  "Cloud & DevOps",
  "Product",
  "Cybersecurity",
  "People",
  "Sales",
  "Operations",
] as const;

export const locations = [
  "All locations",
  "Visakhapatnam",
  "Bengaluru",
  "Hyderabad",
  "Pune",
  "Mumbai",
  "Chennai",
  "Remote",
] as const;
